//! Root-cause hint data structures for cognitive reasoning layer (P0).

use flutter_rust_bridge::frb;

/// A structured hint explaining the *root cause* of a runtime trap,
/// generated by `TraceAnalyzer` and displayed in the Flutter frontend.
#[frb]
#[derive(Debug, Clone, Default)]
pub struct RootCauseHint {
    /// Root-cause category identifier, e.g. "OffByOne", "UseAfterFree",
    /// "UninitializedIndex", "WrongStartIndex", "SizeMismatch", "NullDeref",
    /// "DivZero", "DoubleFree".
    pub category: String,

    /// One-sentence natural-language explanation shown to the student.
    pub one_liner: String,

    /// Source lines related to the root cause (clickable in the IDE).
    pub related_lines: Vec<i32>,

    /// Suggested fix kind, matching existing auto-fix system identifiers:
    /// "ChangeLeToLt", "AddNullCheck", "InitVariable", "FixLoopStart",
    /// "FixArraySize", "SetNullAfterFree", "AvoidDivZero", "None".
    pub suggested_fix_kind: String,

    /// Specific line number where the fix should be applied (if known).
    pub suggested_fix_line: Option<i32>,

    /// Human-readable description of the exact fix (e.g. "将 <= 改为 <").
    pub suggested_fix_desc: Option<String>,
}
