// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A structured hint explaining the *root cause* of a runtime trap,
/// generated by `TraceAnalyzer` and displayed in the Flutter frontend.
class RootCauseHint {
  /// Root-cause category identifier, e.g. "OffByOne", "UseAfterFree",
  /// "UninitializedIndex", "WrongStartIndex", "SizeMismatch", "NullDeref",
  /// "DivZero", "DoubleFree".
  final String category;

  /// One-sentence natural-language explanation shown to the student.
  final String oneLiner;

  /// Source lines related to the root cause (clickable in the IDE).
  final Int32List relatedLines;

  /// Suggested fix kind, matching existing auto-fix system identifiers:
  /// "ChangeLeToLt", "AddNullCheck", "InitVariable", "FixLoopStart",
  /// "FixArraySize", "SetNullAfterFree", "AvoidDivZero", "None".
  final String suggestedFixKind;

  /// Specific line number where the fix should be applied (if known).
  final int? suggestedFixLine;

  /// Human-readable description of the exact fix (e.g. "将 <= 改为 <").
  final String? suggestedFixDesc;

  const RootCauseHint({
    required this.category,
    required this.oneLiner,
    required this.relatedLines,
    required this.suggestedFixKind,
    this.suggestedFixLine,
    this.suggestedFixDesc,
  });

  @override
  int get hashCode =>
      category.hashCode ^
      oneLiner.hashCode ^
      relatedLines.hashCode ^
      suggestedFixKind.hashCode ^
      suggestedFixLine.hashCode ^
      suggestedFixDesc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RootCauseHint &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          oneLiner == other.oneLiner &&
          relatedLines == other.relatedLines &&
          suggestedFixKind == other.suggestedFixKind &&
          suggestedFixLine == other.suggestedFixLine &&
          suggestedFixDesc == other.suggestedFixDesc;
}
