// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'root_cause.dart';
import 'types.dart';

/// 使用符号表的访问变量。
class AccessedVarRef {
  final int nameIdx;
  final int accessTypeIdx;

  const AccessedVarRef({required this.nameIdx, required this.accessTypeIdx});

  @override
  int get hashCode => nameIdx.hashCode ^ accessTypeIdx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccessedVarRef &&
          runtimeType == other.runtimeType &&
          nameIdx == other.nameIdx &&
          accessTypeIdx == other.accessTypeIdx;
}

/// 使用符号表的算法步骤。
class AlgorithmStepSnapshotRef {
  final int algorithmNameIdx;
  final int displayNameIdx;
  final int phaseIdx;
  final int descriptionIdx;

  const AlgorithmStepSnapshotRef({
    required this.algorithmNameIdx,
    required this.displayNameIdx,
    required this.phaseIdx,
    required this.descriptionIdx,
  });

  @override
  int get hashCode =>
      algorithmNameIdx.hashCode ^
      displayNameIdx.hashCode ^
      phaseIdx.hashCode ^
      descriptionIdx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlgorithmStepSnapshotRef &&
          runtimeType == other.runtimeType &&
          algorithmNameIdx == other.algorithmNameIdx &&
          displayNameIdx == other.displayNameIdx &&
          phaseIdx == other.phaseIdx &&
          descriptionIdx == other.descriptionIdx;
}

/// 使用符号表的调用帧。
class ApiFrameInfoRef {
  final int funcNameIdx;
  final int returnLine;

  const ApiFrameInfoRef({required this.funcNameIdx, required this.returnLine});

  @override
  int get hashCode => funcNameIdx.hashCode ^ returnLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiFrameInfoRef &&
          runtimeType == other.runtimeType &&
          funcNameIdx == other.funcNameIdx &&
          returnLine == other.returnLine;
}

/// 使用符号表的变量快照（不变数据 dedup）。
class ApiVarSnapshotRef {
  final int nameIdx;
  final int addr;
  final bool isLocal;
  final int tyNameIdx;
  final String value;

  const ApiVarSnapshotRef({
    required this.nameIdx,
    required this.addr,
    required this.isLocal,
    required this.tyNameIdx,
    required this.value,
  });

  @override
  int get hashCode =>
      nameIdx.hashCode ^
      addr.hashCode ^
      isLocal.hashCode ^
      tyNameIdx.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVarSnapshotRef &&
          runtimeType == other.runtimeType &&
          nameIdx == other.nameIdx &&
          addr == other.addr &&
          isLocal == other.isLocal &&
          tyNameIdx == other.tyNameIdx &&
          value == other.value;
}

/// 使用符号表的数组快照。
class ArraySnapshotRef {
  final int nameIdx;
  final int elementTyIdx;
  final List<String> elements;

  const ArraySnapshotRef({
    required this.nameIdx,
    required this.elementTyIdx,
    required this.elements,
  });

  @override
  int get hashCode =>
      nameIdx.hashCode ^ elementTyIdx.hashCode ^ elements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArraySnapshotRef &&
          runtimeType == other.runtimeType &&
          nameIdx == other.nameIdx &&
          elementTyIdx == other.elementTyIdx &&
          elements == other.elements;
}

/// 使用符号表的指针快照。
class PointerSnapshotRef {
  final int nameIdx;
  final int addr;
  final int tyNameIdx;
  final int targetAddr;
  final int targetNameIdx;
  final PointerStatus status;

  const PointerSnapshotRef({
    required this.nameIdx,
    required this.addr,
    required this.tyNameIdx,
    required this.targetAddr,
    required this.targetNameIdx,
    required this.status,
  });

  @override
  int get hashCode =>
      nameIdx.hashCode ^
      addr.hashCode ^
      tyNameIdx.hashCode ^
      targetAddr.hashCode ^
      targetNameIdx.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PointerSnapshotRef &&
          runtimeType == other.runtimeType &&
          nameIdx == other.nameIdx &&
          addr == other.addr &&
          tyNameIdx == other.tyNameIdx &&
          targetAddr == other.targetAddr &&
          targetNameIdx == other.targetNameIdx &&
          status == other.status;
}

/// 差分 StepPayload（基于前一个 StepPayloadRef 或 StepPayloadDelta）。
class StepPayloadDelta {
  final int stepIndex;
  final int codeLine;
  final int funcNameIdx;
  final int semanticLabelIdx;
  final AlgorithmStepSnapshotRef? algorithmStep;

  /// 值发生变化的变量。
  final List<VarDelta> varDeltas;

  /// 新出现的变量。
  final List<ApiVarSnapshotRef> newVars;

  /// 消失的变量名索引。
  final Int32List removedVarNameIndices;
  final List<ApiFrameInfoRef> callStack;
  final List<VisEvent> visEvents;
  final int heatmapLine;
  final BigInt heatmapCount;
  final List<AccessedVarRef> accessedVars;
  final List<ArraySnapshotRef> arraySnapshots;
  final List<PointerSnapshotRef> pointerSnapshots;
  final RootCauseHint? rootCauseHint;

  const StepPayloadDelta({
    required this.stepIndex,
    required this.codeLine,
    required this.funcNameIdx,
    required this.semanticLabelIdx,
    this.algorithmStep,
    required this.varDeltas,
    required this.newVars,
    required this.removedVarNameIndices,
    required this.callStack,
    required this.visEvents,
    required this.heatmapLine,
    required this.heatmapCount,
    required this.accessedVars,
    required this.arraySnapshots,
    required this.pointerSnapshots,
    this.rootCauseHint,
  });

  @override
  int get hashCode =>
      stepIndex.hashCode ^
      codeLine.hashCode ^
      funcNameIdx.hashCode ^
      semanticLabelIdx.hashCode ^
      algorithmStep.hashCode ^
      varDeltas.hashCode ^
      newVars.hashCode ^
      removedVarNameIndices.hashCode ^
      callStack.hashCode ^
      visEvents.hashCode ^
      heatmapLine.hashCode ^
      heatmapCount.hashCode ^
      accessedVars.hashCode ^
      arraySnapshots.hashCode ^
      pointerSnapshots.hashCode ^
      rootCauseHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepPayloadDelta &&
          runtimeType == other.runtimeType &&
          stepIndex == other.stepIndex &&
          codeLine == other.codeLine &&
          funcNameIdx == other.funcNameIdx &&
          semanticLabelIdx == other.semanticLabelIdx &&
          algorithmStep == other.algorithmStep &&
          varDeltas == other.varDeltas &&
          newVars == other.newVars &&
          removedVarNameIndices == other.removedVarNameIndices &&
          callStack == other.callStack &&
          visEvents == other.visEvents &&
          heatmapLine == other.heatmapLine &&
          heatmapCount == other.heatmapCount &&
          accessedVars == other.accessedVars &&
          arraySnapshots == other.arraySnapshots &&
          pointerSnapshots == other.pointerSnapshots &&
          rootCauseHint == other.rootCauseHint;
}

/// 使用符号表的 StepPayload（基准快照）。
class StepPayloadRef {
  final int stepIndex;
  final int codeLine;
  final int funcNameIdx;
  final int semanticLabelIdx;
  final AlgorithmStepSnapshotRef? algorithmStep;
  final List<ApiVarSnapshotRef> localVars;
  final List<ApiFrameInfoRef> callStack;
  final List<VisEvent> visEvents;
  final int heatmapLine;
  final BigInt heatmapCount;
  final List<AccessedVarRef> accessedVars;
  final List<ArraySnapshotRef> arraySnapshots;
  final List<PointerSnapshotRef> pointerSnapshots;
  final RootCauseHint? rootCauseHint;

  const StepPayloadRef({
    required this.stepIndex,
    required this.codeLine,
    required this.funcNameIdx,
    required this.semanticLabelIdx,
    this.algorithmStep,
    required this.localVars,
    required this.callStack,
    required this.visEvents,
    required this.heatmapLine,
    required this.heatmapCount,
    required this.accessedVars,
    required this.arraySnapshots,
    required this.pointerSnapshots,
    this.rootCauseHint,
  });

  @override
  int get hashCode =>
      stepIndex.hashCode ^
      codeLine.hashCode ^
      funcNameIdx.hashCode ^
      semanticLabelIdx.hashCode ^
      algorithmStep.hashCode ^
      localVars.hashCode ^
      callStack.hashCode ^
      visEvents.hashCode ^
      heatmapLine.hashCode ^
      heatmapCount.hashCode ^
      accessedVars.hashCode ^
      arraySnapshots.hashCode ^
      pointerSnapshots.hashCode ^
      rootCauseHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepPayloadRef &&
          runtimeType == other.runtimeType &&
          stepIndex == other.stepIndex &&
          codeLine == other.codeLine &&
          funcNameIdx == other.funcNameIdx &&
          semanticLabelIdx == other.semanticLabelIdx &&
          algorithmStep == other.algorithmStep &&
          localVars == other.localVars &&
          callStack == other.callStack &&
          visEvents == other.visEvents &&
          heatmapLine == other.heatmapLine &&
          heatmapCount == other.heatmapCount &&
          accessedVars == other.accessedVars &&
          arraySnapshots == other.arraySnapshots &&
          pointerSnapshots == other.pointerSnapshots &&
          rootCauseHint == other.rootCauseHint;
}

/// Stream 批量传输单元。
///
/// 编码规则：
/// - `base_payloads` 包含每 batch 的第 1 个完整快照（step 0）。
/// - `deltas` 包含后续步的差分数据（基于前一步的局部变量状态）。
/// - `symbol_table` 全局去重字符串池。
class StepStreamBatch {
  final List<String> symbolTable;
  final List<StepPayloadRef> basePayloads;
  final List<StepPayloadDelta> deltas;
  final bool finished;
  final bool trapped;
  final bool waitingInput;
  final bool paused;
  final int currentLine;
  final String? trapMessage;

  const StepStreamBatch({
    required this.symbolTable,
    required this.basePayloads,
    required this.deltas,
    required this.finished,
    required this.trapped,
    required this.waitingInput,
    required this.paused,
    required this.currentLine,
    this.trapMessage,
  });

  @override
  int get hashCode =>
      symbolTable.hashCode ^
      basePayloads.hashCode ^
      deltas.hashCode ^
      finished.hashCode ^
      trapped.hashCode ^
      waitingInput.hashCode ^
      paused.hashCode ^
      currentLine.hashCode ^
      trapMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepStreamBatch &&
          runtimeType == other.runtimeType &&
          symbolTable == other.symbolTable &&
          basePayloads == other.basePayloads &&
          deltas == other.deltas &&
          finished == other.finished &&
          trapped == other.trapped &&
          waitingInput == other.waitingInput &&
          paused == other.paused &&
          currentLine == other.currentLine &&
          trapMessage == other.trapMessage;
}

/// 差分变量：仅包含值发生变化的变量。
class VarDelta {
  final int nameIdx;
  final String value;

  const VarDelta({required this.nameIdx, required this.value});

  @override
  int get hashCode => nameIdx.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VarDelta &&
          runtimeType == other.runtimeType &&
          nameIdx == other.nameIdx &&
          value == other.value;
}
