// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'root_cause.dart';

/// 当前步访问的变量（用于变量级高亮）。
class AccessedVar {
  final String name;
  final String accessType;

  const AccessedVar({required this.name, required this.accessType});

  @override
  int get hashCode => name.hashCode ^ accessType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccessedVar &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          accessType == other.accessType;
}

/// 算法步骤语义快照（用于前端步骤标注）。
class AlgorithmStepSnapshot {
  final String algorithmName;
  final String displayName;
  final String phase;
  final String description;

  const AlgorithmStepSnapshot({
    required this.algorithmName,
    required this.displayName,
    required this.phase,
    required this.description,
  });

  @override
  int get hashCode =>
      algorithmName.hashCode ^
      displayName.hashCode ^
      phase.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlgorithmStepSnapshot &&
          runtimeType == other.runtimeType &&
          algorithmName == other.algorithmName &&
          displayName == other.displayName &&
          phase == other.phase &&
          description == other.description;
}

/// FRB 友好的调用帧信息。
class ApiFrameInfo {
  final String funcName;
  final int returnLine;

  const ApiFrameInfo({required this.funcName, required this.returnLine});

  @override
  int get hashCode => funcName.hashCode ^ returnLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiFrameInfo &&
          runtimeType == other.runtimeType &&
          funcName == other.funcName &&
          returnLine == other.returnLine;
}

/// FRB 友好的变量快照（ty 已格式化为字符串）。
class ApiVariableSnapshot {
  final String name;
  final int addr;
  final bool isLocal;
  final String tyName;
  final String value;

  const ApiVariableSnapshot({
    required this.name,
    required this.addr,
    required this.isLocal,
    required this.tyName,
    required this.value,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      addr.hashCode ^
      isLocal.hashCode ^
      tyName.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVariableSnapshot &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          addr == other.addr &&
          isLocal == other.isLocal &&
          tyName == other.tyName &&
          value == other.value;
}

/// 数组变量快照（用于算法可视化条形图）。
class ArraySnapshot {
  final String name;
  final String elementTy;
  final List<String> elements;

  const ArraySnapshot({
    required this.name,
    required this.elementTy,
    required this.elements,
  });

  @override
  int get hashCode => name.hashCode ^ elementTy.hashCode ^ elements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArraySnapshot &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          elementTy == other.elementTy &&
          elements == other.elements;
}

/// 批量自动执行的返回结果。
class AutoStepResult {
  final List<StepPayload> payloads;
  final bool finished;
  final bool trapped;
  final bool waitingInput;
  final bool paused;
  final int currentLine;
  final String? trapMessage;

  const AutoStepResult({
    required this.payloads,
    required this.finished,
    required this.trapped,
    required this.waitingInput,
    required this.paused,
    required this.currentLine,
    this.trapMessage,
  });

  @override
  int get hashCode =>
      payloads.hashCode ^
      finished.hashCode ^
      trapped.hashCode ^
      waitingInput.hashCode ^
      paused.hashCode ^
      currentLine.hashCode ^
      trapMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutoStepResult &&
          runtimeType == other.runtimeType &&
          payloads == other.payloads &&
          finished == other.finished &&
          trapped == other.trapped &&
          waitingInput == other.waitingInput &&
          paused == other.paused &&
          currentLine == other.currentLine &&
          trapMessage == other.trapMessage;
}

/// 执行热力图数据。
class HeatmapData {
  final List<(int, BigInt)> lineCounts;
  final BigInt maxCount;

  const HeatmapData({required this.lineCounts, required this.maxCount});

  @override
  int get hashCode => lineCounts.hashCode ^ maxCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeatmapData &&
          runtimeType == other.runtimeType &&
          lineCounts == other.lineCounts &&
          maxCount == other.maxCount;
}

/// 指针变量快照（用于指针追踪动画）。
class PointerSnapshot {
  final String name;
  final int addr;
  final String tyName;
  final int targetAddr;
  final String targetName;
  final PointerStatus status;

  const PointerSnapshot({
    required this.name,
    required this.addr,
    required this.tyName,
    required this.targetAddr,
    required this.targetName,
    required this.status,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      addr.hashCode ^
      tyName.hashCode ^
      targetAddr.hashCode ^
      targetName.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PointerSnapshot &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          addr == other.addr &&
          tyName == other.tyName &&
          targetAddr == other.targetAddr &&
          targetName == other.targetName &&
          status == other.status;
}

/// 指针状态。
enum PointerStatus {
  /// 指向有效内存（栈、全局、已分配堆）。
  valid,

  /// 指向已释放的堆内存。
  freed,

  /// NULL 指针。
  null_,

  /// 悬空指针（越界或未初始化）。
  dangling,
}

/// Seek 到指定步的返回结果。
class SeekResult {
  final bool success;
  final StepPayload? payload;
  final String? error;

  const SeekResult({required this.success, this.payload, this.error});

  @override
  int get hashCode => success.hashCode ^ payload.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeekResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          payload == other.payload &&
          error == other.error;
}

/// 每步的轻量数据包，传输到 Flutter 前端作为 FrameCache。
class StepPayload {
  final int stepIndex;
  final int codeLine;
  final String funcName;
  final String semanticLabel;
  final AlgorithmStepSnapshot? algorithmStep;
  final List<ApiVariableSnapshot> localVars;
  final List<ApiFrameInfo> callStack;
  final List<VisEvent> visEvents;
  final int heatmapLine;
  final BigInt heatmapCount;
  final List<AccessedVar> accessedVars;
  final List<ArraySnapshot> arraySnapshots;
  final List<PointerSnapshot> pointerSnapshots;
  final RootCauseHint? rootCauseHint;

  const StepPayload({
    required this.stepIndex,
    required this.codeLine,
    required this.funcName,
    required this.semanticLabel,
    this.algorithmStep,
    required this.localVars,
    required this.callStack,
    required this.visEvents,
    required this.heatmapLine,
    required this.heatmapCount,
    required this.accessedVars,
    required this.arraySnapshots,
    required this.pointerSnapshots,
    this.rootCauseHint,
  });

  @override
  int get hashCode =>
      stepIndex.hashCode ^
      codeLine.hashCode ^
      funcName.hashCode ^
      semanticLabel.hashCode ^
      algorithmStep.hashCode ^
      localVars.hashCode ^
      callStack.hashCode ^
      visEvents.hashCode ^
      heatmapLine.hashCode ^
      heatmapCount.hashCode ^
      accessedVars.hashCode ^
      arraySnapshots.hashCode ^
      pointerSnapshots.hashCode ^
      rootCauseHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepPayload &&
          runtimeType == other.runtimeType &&
          stepIndex == other.stepIndex &&
          codeLine == other.codeLine &&
          funcName == other.funcName &&
          semanticLabel == other.semanticLabel &&
          algorithmStep == other.algorithmStep &&
          localVars == other.localVars &&
          callStack == other.callStack &&
          visEvents == other.visEvents &&
          heatmapLine == other.heatmapLine &&
          heatmapCount == other.heatmapCount &&
          accessedVars == other.accessedVars &&
          arraySnapshots == other.arraySnapshots &&
          pointerSnapshots == other.pointerSnapshots &&
          rootCauseHint == other.rootCauseHint;
}

/// 编译并启动统一模式的返回结果。
class UnifiedRunResult {
  final bool success;
  final String? error;
  final int totalSteps;
  final bool finished;

  const UnifiedRunResult({
    required this.success,
    this.error,
    required this.totalSteps,
    required this.finished,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      error.hashCode ^
      totalSteps.hashCode ^
      finished.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnifiedRunResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error &&
          totalSteps == other.totalSteps &&
          finished == other.finished;
}
