// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB 友好的调用帧信息。
class ApiFrameInfo {
  final String funcName;
  final int returnLine;

  const ApiFrameInfo({required this.funcName, required this.returnLine});

  @override
  int get hashCode => funcName.hashCode ^ returnLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiFrameInfo &&
          runtimeType == other.runtimeType &&
          funcName == other.funcName &&
          returnLine == other.returnLine;
}

/// FRB 友好的变量快照（ty 已格式化为字符串）。
class ApiVariableSnapshot {
  final String name;
  final int addr;
  final bool isLocal;
  final String tyName;
  final String value;

  const ApiVariableSnapshot({
    required this.name,
    required this.addr,
    required this.isLocal,
    required this.tyName,
    required this.value,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      addr.hashCode ^
      isLocal.hashCode ^
      tyName.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVariableSnapshot &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          addr == other.addr &&
          isLocal == other.isLocal &&
          tyName == other.tyName &&
          value == other.value;
}

/// 批量自动执行的返回结果。
class AutoStepResult {
  final List<StepPayload> payloads;
  final bool finished;
  final bool trapped;
  final bool waitingInput;
  final int currentLine;

  const AutoStepResult({
    required this.payloads,
    required this.finished,
    required this.trapped,
    required this.waitingInput,
    required this.currentLine,
  });

  @override
  int get hashCode =>
      payloads.hashCode ^
      finished.hashCode ^
      trapped.hashCode ^
      waitingInput.hashCode ^
      currentLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutoStepResult &&
          runtimeType == other.runtimeType &&
          payloads == other.payloads &&
          finished == other.finished &&
          trapped == other.trapped &&
          waitingInput == other.waitingInput &&
          currentLine == other.currentLine;
}

/// 执行热力图数据。
class HeatmapData {
  final List<(int, BigInt)> lineCounts;
  final BigInt maxCount;

  const HeatmapData({required this.lineCounts, required this.maxCount});

  @override
  int get hashCode => lineCounts.hashCode ^ maxCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeatmapData &&
          runtimeType == other.runtimeType &&
          lineCounts == other.lineCounts &&
          maxCount == other.maxCount;
}

/// Seek 到指定步的返回结果。
class SeekResult {
  final bool success;
  final StepPayload? payload;
  final String? error;

  const SeekResult({required this.success, this.payload, this.error});

  @override
  int get hashCode => success.hashCode ^ payload.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeekResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          payload == other.payload &&
          error == other.error;
}

/// 每步的轻量数据包，传输到 Flutter 前端作为 FrameCache。
class StepPayload {
  final int stepIndex;
  final int codeLine;
  final String funcName;
  final String semanticLabel;
  final List<ApiVariableSnapshot> localVars;
  final List<ApiFrameInfo> callStack;
  final List<VisEvent> visEvents;
  final int heatmapLine;
  final BigInt heatmapCount;

  const StepPayload({
    required this.stepIndex,
    required this.codeLine,
    required this.funcName,
    required this.semanticLabel,
    required this.localVars,
    required this.callStack,
    required this.visEvents,
    required this.heatmapLine,
    required this.heatmapCount,
  });

  @override
  int get hashCode =>
      stepIndex.hashCode ^
      codeLine.hashCode ^
      funcName.hashCode ^
      semanticLabel.hashCode ^
      localVars.hashCode ^
      callStack.hashCode ^
      visEvents.hashCode ^
      heatmapLine.hashCode ^
      heatmapCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepPayload &&
          runtimeType == other.runtimeType &&
          stepIndex == other.stepIndex &&
          codeLine == other.codeLine &&
          funcName == other.funcName &&
          semanticLabel == other.semanticLabel &&
          localVars == other.localVars &&
          callStack == other.callStack &&
          visEvents == other.visEvents &&
          heatmapLine == other.heatmapLine &&
          heatmapCount == other.heatmapCount;
}

/// 编译并启动统一模式的返回结果。
class UnifiedRunResult {
  final bool success;
  final String? error;
  final int totalSteps;
  final bool finished;

  const UnifiedRunResult({
    required this.success,
    this.error,
    required this.totalSteps,
    required this.finished,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      error.hashCode ^
      totalSteps.hashCode ^
      finished.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnifiedRunResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error &&
          totalSteps == other.totalSteps &&
          finished == other.finished;
}
