//! Lexer 公共类型定义。

/// 词法单元类型。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenType {
    Int,
    Void,
    Char,
    If,
    Else,
    While,
    Do,
    For,
    Return,
    Break,
    Continue,
    Struct,
    Union,
    Sizeof,
    Offsetof,
    Alignof,
    Generic,
    Switch,
    Case,
    Default,
    Typedef,
    Enum,
    Unsigned,
    Long,
    Short,
    Signed,
    Const,
    Extern,
    Float,
    Double,
    Volatile,
    Inline,
    Restrict,
    Register,
    Auto,
    Bool,
    Goto,
    Null,
    // === C++ 新增关键字 ===
    Class,
    Public,
    Private,
    Protected,
    This,
    Using,
    Namespace,
    Virtual,
    Override,
    Explicit,
    Friend,
    Template,
    Typename,
    StaticCast,
    ConstCast,
    ReinterpretCast,
    New,
    Delete,
    // === C++ 新增标点 ===
    ColonColon,
    ArrowStar,
    DotStar,
    Identifier,
    Number,
    UnsignedLiteral,
    FloatLiteral,
    LongLiteral,
    CharLiteral,
    String,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    AndAnd,
    OrOr,
    Not,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AndAssign,
    OrAssign,
    XorAssign,
    ShlAssign,
    ShrAssign,
    Ampersand,
    BitOr,
    BitXor,
    BitNot,
    Shl,
    Shr,
    Increment,
    Decrement,
    Semicolon,
    Comma,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Dot,
    Ellipsis,
    Arrow,
    Colon,
    Question,
    Eof,
    Unknown,
    /// E2：`#`（仅宏体内作字符串化操作符；其余上下文仍按预处理指令消费）
    Hash,
    /// E2：`##`（宏体内 token 拼接操作符）
    HashHash,
}

/// 词法单元。
#[derive(Debug, Clone)]
pub struct Token {
    pub ty: TokenType,
    pub text: String,
    pub line: i32,
    pub column: i32,
}

/// 词法错误。
#[derive(Debug, Clone)]
pub struct LexerError {
    pub message: String,
    pub line: i32,
    pub column: i32,
    pub code: i32,
}

/// E2 白箱教学层：预处理阶段**非致命**提示（宏遮蔽、宏参数副作用等）。
/// 与 `LexerError`（致命，终止编译）分流——警告经管线进 diagnostics（severity=1）。
#[derive(Debug, Clone)]
pub struct LexerWarning {
    pub message: String,
    pub line: i32,
    pub column: i32,
    pub code: i32,
}
