cases = [
    ("multi_if_else", 'int main() { int x = 2; if (x == 1) printf("one"); else if (x == 2) printf("two"); else printf("other"); return 0; }'),
    ("if_nested", 'int main() { int a = 1, b = 2; if (a == 1) { if (b == 2) printf("yes"); } return 0; }'),
    ("switch_default_first", 'int main() { int x = 5; switch(x) { default: printf("def"); break; case 1: printf("one"); break; } return 0; }'),
    ("for_no_init", 'int main() { int i = 0; for (; i < 3; i++) printf("%d", i); return 0; }'),
    ("for_no_incr", 'int main() { int i = 0; for (; i < 3; ) { printf("%d", i); i++; } return 0; }'),
    ("while_nested", 'int main() { int i = 0; while (i < 2) { int j = 0; while (j < 2) { printf("%d", i+j); j++; } i++; } return 0; }'),
    ("do_while_continue", 'int main() { int i = 0; do { i++; if (i == 2) continue; printf("%d", i); } while (i < 4); return 0; }'),
    ("break_in_nested_loop", 'int main() { for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (j == 1) break; printf("%d", i+j); } } return 0; }'),
    ("short_circuit_and", 'int f() { printf("call"); return 1; } int main() { int x = 0; if (x && f()) printf("yes"); printf("done"); return 0; }'),
    ("short_circuit_or", 'int f() { printf("call"); return 1; } int main() { int x = 1; if (x || f()) printf("yes"); printf("done"); return 0; }'),
    ("ternary_as_expr", 'int main() { int a = 5, b = 3; int m = (a > b ? a : b) + 1; printf("%d", m); return 0; }'),
    ("assign_chain", 'int main() { int a, b, c; a = b = c = 5; printf("%d %d %d", a, b, c); return 0; }'),
    ("precedence", 'int main() { printf("%d", 2 + 3 * 4); return 0; }'),
    ("parentheses_priority", 'int main() { printf("%d", (2 + 3) * 4); return 0; }'),
    ("post_inc_vs_pre_inc", 'int main() { int i = 5; printf("%d", i++); printf("%d", ++i); return 0; }'),
    ("neg_modulo", 'int main() { printf("%d", -17 % 5); return 0; }'),
    ("bitwise_combo", 'int main() { printf("%d", ((5 & 3) | 6) ^ 1); return 0; }'),
    ("shift_zero", 'int main() { printf("%d", 1 << 0); return 0; }'),
    ("shift_31", 'int main() { printf("%d", 1 << 31); return 0; }'),
    ("not_zero", 'int main() { printf("%d", ~0); return 0; }'),
    ("double_compare", 'int main() { double d = 3.14; printf("%d", d > 3.0); return 0; }'),
    ("double_array_op", 'int main() { double arr[2] = {1.5, 2.5}; printf("%.1f", arr[0] + arr[1]); return 0; }'),
    ("enum_non_continuous", 'enum E { A = 10, B = 20 }; int main() { printf("%d", B); return 0; }'),
    ("sizeof_typedef", 'typedef int Integer; int main() { printf("%d", sizeof(Integer)); return 0; }'),
    ("sizeof_enum", 'enum Color { R, G }; int main() { printf("%d", sizeof(enum Color)); return 0; }'),
    ("zero_init_array", 'int main() { int a[5] = {0}; printf("%d", a[4]); return 0; }'),
    ("array_no_size", 'int main() { int a[] = {1, 2, 3}; printf("%d", a[2]); return 0; }'),
    ("global_var_init", 'int g = 7; int main() { printf("%d", g); return 0; }'),
    ("typedef_chain", 'typedef int A; typedef A B; int main() { B x = 5; printf("%d", x); return 0; }'),
    ("void_param", 'int f(void) { return 1; } int main() { printf("%d", f()); return 0; }'),
    ("func_many_params", 'int sum(int a, int b, int c, int d, int e) { return a+b+c+d+e; } int main() { printf("%d", sum(1,2,3,4,5)); return 0; }'),
    ("printf_char", 'int main() { printf("%c", \'A\'); return 0; }'),
    ("realloc_shrink", 'int main() { int* p = malloc(8); p[0] = 1; p[1] = 2; p = realloc(p, 4); printf("%d", p[0]); free(p); return 0; }'),
    ("memset_struct", 'struct S { int a; int b; }; int main() { struct S s; memset(&s, 0, sizeof(s)); printf("%d", s.a); return 0; }'),
    ("strcat_empty", 'int main() { char a[10] = "a"; strcat(a, ""); printf("%s", a); return 0; }'),
    ("atoi_negative", 'int main() { printf("%d", atoi("-42")); return 0; }'),
    ("define_in_expr", '#define TEN 10\nint main() { printf("%d", TEN + 5); return 0; }'),
    ("empty_func", 'void f() {} int main() { f(); printf("ok"); return 0; }'),
    ("switch_empty", 'int main() { int x = 1; switch(x) {} printf("ok"); return 0; }'),
    ("switch_fallthrough", 'int main() { int x = 1; switch(x) { case 1: case 2: printf("ok"); break; } return 0; }'),
    ("double_assign", 'int main() { double d = 3.14; d = 2.71; printf("%.2f", d); return 0; }'),
    ("int_div", 'int main() { printf("%d", 7 / 3); return 0; }'),
    ("int_div_neg", 'int main() { printf("%d", -7 / 3); return 0; }'),
    ("mul_overflow_safe", 'int main() { printf("%d", 1000 * 1000); return 0; }'),
    ("compare_eq", 'int main() { printf("%d", 5 == 5); return 0; }'),
    ("compare_lt_eq", 'int main() { printf("%d", 5 <= 5); return 0; }'),
    ("compare_gt_eq", 'int main() { printf("%d", 5 >= 3); return 0; }'),
    ("bool_from_compare", 'int main() { int b = 5 > 3; printf("%d", b); return 0; }'),
    ("char_signedness", 'int main() { char c = -1; printf("%d", c); return 0; }'),
    ("array_bounds_safe", 'int main() { int a[5] = {0,1,2,3,4}; printf("%d", a[4]); return 0; }'),
    ("ptr_init_null", 'int main() { int* p = NULL; printf("%d", p == NULL); return 0; }'),
    ("struct_copy", 'struct S { int a; int b; }; int main() { struct S s1 = {1, 2}; struct S s2 = s1; printf("%d %d", s2.a, s2.b); return 0; }'),
    ("union_size_access", 'union U { char c; int i; }; int main() { printf("%d", sizeof(union U)); return 0; }'),
    ("nested_ternary", 'int main() { int a = 1, b = 2, c = 3; int r = a ? b : c; printf("%d", r); return 0; }'),
    ("loop_var_shadow", 'int main() { int i = 10; for (int i = 0; i < 3; i++) printf("%d", i); printf("%d", i); return 0; }'),
    ("func_ptr_param_decay", 'int sum(int a[]) { int s = 0; for (int i = 0; i < 3; i++) s += a[i]; return s; } int main() { int arr[3] = {1,2,3}; printf("%d", sum(arr)); return 0; }'),
    ("double_init_zero", 'int main() { double d = 0.0; printf("%.0f", d); return 0; }'),
    ("sizeof_double_arr", 'int main() { double a[3]; printf("%d", sizeof(a)); return 0; }'),
    ("sizeof_float_arr", 'int main() { float a[3]; printf("%d", sizeof(a)); return 0; }'),
    ("sizeof_long_long", 'int main() { printf("%d", sizeof(long long)); return 0; }'),
    ("union_int_member", 'union U { int i; float f; }; int main() { union U u; u.i = 42; printf("%d", u.i); return 0; }'),
    ("struct_member_array", 'struct S { int arr[3]; }; int main() { struct S s; s.arr[1] = 5; printf("%d", s.arr[1]); return 0; }'),
    ("ptr_to_struct_member", 'struct S { int x; }; int main() { struct S s; struct S* p = &s; p->x = 7; printf("%d", p->x); return 0; }'),
    ("array_of_union", 'union U { int i; }; int main() { union U arr[2]; arr[0].i = 1; arr[1].i = 2; printf("%d", arr[1].i); return 0; }'),
    ("ptr_arith_char", 'int main() { char arr[3] = {\'a\', \'b\', \'c\'}; char* p = arr; p++; printf("%c", *p); return 0; }'),
    ("ptr_arith_struct", 'struct S { int x; }; int main() { struct S arr[2]; struct S* p = arr; p++; printf("%d", p == &arr[1]); return 0; }'),
    ("nested_ternary2", 'int main() { int a = 1, b = 2, c = 3; printf("%d", a > b ? c : (b > c ? a : b)); return 0; }'),
    ("for_break", 'int main() { for (int i = 0; i < 10; i++) { if (i == 3) break; printf("%d", i); } return 0; }'),
    ("for_continue", 'int main() { for (int i = 0; i < 5; i++) { if (i == 2) continue; printf("%d", i); } return 0; }'),
    ("while_continue", 'int main() { int i = 0; while (i < 5) { i++; if (i == 2) continue; printf("%d", i); } return 0; }'),
    ("do_while_break", 'int main() { int i = 0; do { if (i == 2) break; printf("%d", i); i++; } while (i < 5); return 0; }'),
    ("empty_for", 'int main() { for (int i = 0; i < 0; i++) printf("no"); printf("ok"); return 0; }'),
    ("empty_while", 'int main() { while (0) printf("no"); printf("ok"); return 0; }'),
    ("empty_if", 'int main() { if (0) printf("no"); printf("ok"); return 0; }'),
    ("negate", 'int main() { int x = 5; printf("%d", -x); return 0; }'),
    ("bit_not_zero", 'int main() { int x = 0; printf("%d", ~x); return 0; }'),
    ("bit_xor", 'int main() { printf("%d", 5 ^ 3); return 0; }'),
    ("shl_rhs", 'int main() { int x = 2; printf("%d", 1 << x); return 0; }'),
    ("shr_rhs", 'int main() { int x = 2; printf("%d", 8 >> x); return 0; }'),
    ("div_by_var", 'int main() { int x = 3; printf("%d", 10 / x); return 0; }'),
    ("mod_by_var", 'int main() { int x = 4; printf("%d", 10 % x); return 0; }'),
    ("mul_by_var", 'int main() { int x = 5; printf("%d", x * 6); return 0; }'),
    ("sub_by_var", 'int main() { int x = 3; printf("%d", 10 - x); return 0; }'),
    ("compare_var", 'int main() { int a = 5, b = 3; printf("%d", a > b); return 0; }'),
    ("equal_var", 'int main() { int a = 5, b = 5; printf("%d", a == b); return 0; }'),
    ("not_equal_var", 'int main() { int a = 5, b = 3; printf("%d", a != b); return 0; }'),
    ("logical_and_var", 'int main() { int a = 1, b = 0; printf("%d", a && b); return 0; }'),
    ("logical_or_var", 'int main() { int a = 0, b = 0; printf("%d", a || b); return 0; }'),
    ("logical_not_var", 'int main() { int a = 1; printf("%d", !a); return 0; }'),
    ("increment_var", 'int main() { int x = 5; x++; printf("%d", x); return 0; }'),
    ("decrement_var", 'int main() { int x = 5; x--; printf("%d", x); return 0; }'),
    ("compound_add_var", 'int main() { int x = 5; x += 3; printf("%d", x); return 0; }'),
    ("compound_sub_var", 'int main() { int x = 5; x -= 3; printf("%d", x); return 0; }'),
    ("compound_mul_var", 'int main() { int x = 5; x *= 3; printf("%d", x); return 0; }'),
    ("compound_div_var", 'int main() { int x = 6; x /= 3; printf("%d", x); return 0; }'),
    ("compound_mod_var", 'int main() { int x = 7; x %= 3; printf("%d", x); return 0; }'),
    ("ptr_assign_deref", 'int main() { int x = 5; int* p = &x; *p = 10; printf("%d", x); return 0; }'),
    ("ptr_compare_null", 'int main() { int* p = NULL; printf("%d", p == NULL); return 0; }'),
    ("ptr_compare_not_null", 'int main() { int x = 5; int* p = &x; printf("%d", p != NULL); return 0; }'),
    ("array_sum_loop", 'int main() { int a[3] = {1,2,3}; int s = 0; for (int i = 0; i < 3; i++) s += a[i]; printf("%d", s); return 0; }'),
    ("array_max", 'int main() { int a[3] = {3,1,2}; int m = a[0]; for (int i = 1; i < 3; i++) if (a[i] > m) m = a[i]; printf("%d", m); return 0; }'),
    ("swap_by_ptr", 'void swap(int* a, int* b) { int t = *a; *a = *b; *b = t; } int main() { int x = 1, y = 2; swap(&x, &y); printf("%d %d", x, y); return 0; }'),
    ("factorial", 'int fact(int n) { if (n <= 1) return 1; return n * fact(n-1); } int main() { printf("%d", fact(6)); return 0; }'),
    ("fibonacci", 'int fib(int n) { if (n <= 1) return n; return fib(n-1) + fib(n-2); } int main() { printf("%d", fib(10)); return 0; }'),
    ("sum_1_to_n", 'int main() { int n = 10, s = 0; for (int i = 1; i <= n; i++) s += i; printf("%d", s); return 0; }'),
    ("is_prime", 'int main() { int n = 17, is_p = 1; for (int i = 2; i * i <= n; i++) if (n % i == 0) is_p = 0; printf("%d", is_p); return 0; }'),
    ("gcd_euclid", 'int gcd(int a, int b) { while (b != 0) { int t = b; b = a % b; a = t; } return a; } int main() { printf("%d", gcd(48, 18)); return 0; }'),
    ("bubble_sort", 'int main() { int a[5] = {5,3,4,1,2}; for (int i = 0; i < 4; i++) for (int j = 0; j < 4-i; j++) if (a[j] > a[j+1]) { int t = a[j]; a[j] = a[j+1]; a[j+1] = t; } printf("%d", a[0]); return 0; }'),
    ("linear_search", 'int main() { int a[5] = {1,3,5,7,9}; int key = 7, found = -1; for (int i = 0; i < 5; i++) if (a[i] == key) { found = i; break; } printf("%d", found); return 0; }'),
    ("reverse_array", 'int main() { int a[5] = {1,2,3,4,5}; for (int i = 0; i < 2; i++) { int t = a[i]; a[i] = a[4-i]; a[4-i] = t; } printf("%d", a[0]); return 0; }'),
    ("sum_of_digits", 'int main() { int n = 123, s = 0; while (n > 0) { s += n % 10; n /= 10; } printf("%d", s); return 0; }'),
    ("power_of_2", 'int main() { int n = 16; printf("%d", (n & (n-1)) == 0); return 0; }'),
    ("string_len_manual", 'int main() { char* s = "hello"; int len = 0; while (s[len]) len++; printf("%d", len); return 0; }'),
    ("memcpy_manual", 'int main() { int src[3] = {1,2,3}; int dst[3]; for (int i = 0; i < 3; i++) dst[i] = src[i]; printf("%d", dst[2]); return 0; }'),
    ("matrix_trace", 'int main() { int a[2][2] = {{1,2},{3,4}}; int trace = a[0][0] + a[1][1]; printf("%d", trace); return 0; }'),
    # ---- 函数指针 (C子集新增) ----
    ("function_pointer_decl", 'int add(int a, int b) { return a+b; } int main() { int (*fp)(int,int) = add; printf("%d", fp(1,2)); return 0; }'),
    ("function_pointer_array", 'int f1() { return 1; } int f2() { return 2; } int main() { int (*fp[2])() = {f1,f2}; printf("%d %d", fp[0](), fp[1]()); return 0; }'),
    ("function_pointer_arg", 'int apply(int (*op)(int), int x) { return op(x); } int inc(int n) { return n+1; } int main() { printf("%d", apply(inc, 5)); return 0; }'),
    ("function_pointer_typedef", 'typedef int (*Op)(int, int); int add(int a, int b) { return a+b; } int main() { Op op = add; printf("%d", op(2,3)); return 0; }'),
    ("function_pointer_sizeof", 'int main() { printf("%d", sizeof(int (*)(int))); return 0; }'),  # Cide=4, Clang64=8 (known arch diff)
    ("function_pointer_multi_level", 'int add(int a) { return a+1; } int main() { int (*fp)(int) = add; int (**pp)(int) = &fp; printf("%d", (*pp)(5)); return 0; }'),
    ("function_pointer_return_ptr", 'int* greet(int x) { static int r = 0; r = x; return &r; } int main() { int* (*fp)(int) = greet; int* p = fp(42); printf("%d", *p); return 0; }'),
    ("function_pointer_array_direct", 'int mul(int a, int b) { return a*b; } int divi(int a, int b) { return a/b; } int main() { int (*ops[2])(int, int) = {mul, divi}; printf("%d %d", ops[0](3,4), ops[1](8,2)); return 0; }'),
    ("function_pointer_local_typedef", 'int add(int a, int b) { return a+b; } int main() { typedef int (*Op)(int, int); Op op = add; printf("%d", op(2,3)); return 0; }'),
    # ---- double (C子集新增) ----
    ("double_basic", 'int main() { double d = 3.1415926535; printf("%.10f", d); return 0; }'),
    ("double_arr", 'int main() { double arr[3] = {1.1, 2.2, 3.3}; printf("%.1f", arr[1]); return 0; }'),
    ("double_printf_lf", 'int main() { double d = 3.14; printf("%lf", d); return 0; }'),
    ("double_arith", 'int main() { double a = 1.5, b = 2.5; printf("%.1f", a + b); return 0; }'),
    ("double_mul", 'int main() { double a = 2.0, b = 3.0; printf("%.1f", a * b); return 0; }'),
    ("double_cast_int", 'int main() { double d = 3.9; printf("%d", (int)d); return 0; }'),
    ("double_cmp_eq", 'int main() { double a = 2.5, b = 2.5; printf("%d", a == b); return 0; }'),
]

lines = []
for name, src in cases:
    lines.append(f'    ShadowCase("{name}", \'{src}\', "baseline"),')

print("\n".join(lines))
