// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AlgorithmMatch {
  final String name;
  final String displayName;
  final String funcName;
  final int confidence;
  final String suggestion;
  final int line;
  final List<VisEvent> visEvents;

  const AlgorithmMatch({
    required this.name,
    required this.displayName,
    required this.funcName,
    required this.confidence,
    required this.suggestion,
    required this.line,
    required this.visEvents,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      funcName.hashCode ^
      confidence.hashCode ^
      suggestion.hashCode ^
      line.hashCode ^
      visEvents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlgorithmMatch &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          funcName == other.funcName &&
          confidence == other.confidence &&
          suggestion == other.suggestion &&
          line == other.line &&
          visEvents == other.visEvents;
}

class CompileResult {
  final bool success;
  final List<Diagnostic> diagnostics;
  final List<AlgorithmMatch> algorithmMatches;

  const CompileResult({
    required this.success,
    required this.diagnostics,
    required this.algorithmMatches,
  });

  @override
  int get hashCode =>
      success.hashCode ^ diagnostics.hashCode ^ algorithmMatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          diagnostics == other.diagnostics &&
          algorithmMatches == other.algorithmMatches;
}

class Diagnostic {
  final int line;
  final int column;
  final int errorCode;
  final int severity;
  final String message;
  final String fixSuggestion;
  final int fixKind;
  final int replaceStartLine;
  final int replaceStartColumn;
  final int replaceEndLine;
  final int replaceEndColumn;
  final String replacementText;
  final String filename;

  const Diagnostic({
    required this.line,
    required this.column,
    required this.errorCode,
    required this.severity,
    required this.message,
    required this.fixSuggestion,
    required this.fixKind,
    required this.replaceStartLine,
    required this.replaceStartColumn,
    required this.replaceEndLine,
    required this.replaceEndColumn,
    required this.replacementText,
    required this.filename,
  });

  @override
  int get hashCode =>
      line.hashCode ^
      column.hashCode ^
      errorCode.hashCode ^
      severity.hashCode ^
      message.hashCode ^
      fixSuggestion.hashCode ^
      fixKind.hashCode ^
      replaceStartLine.hashCode ^
      replaceStartColumn.hashCode ^
      replaceEndLine.hashCode ^
      replaceEndColumn.hashCode ^
      replacementText.hashCode ^
      filename.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Diagnostic &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          column == other.column &&
          errorCode == other.errorCode &&
          severity == other.severity &&
          message == other.message &&
          fixSuggestion == other.fixSuggestion &&
          fixKind == other.fixKind &&
          replaceStartLine == other.replaceStartLine &&
          replaceStartColumn == other.replaceStartColumn &&
          replaceEndLine == other.replaceEndLine &&
          replaceEndColumn == other.replaceEndColumn &&
          replacementText == other.replacementText &&
          filename == other.filename;
}

class MemoryRegion {
  final int addr;
  final int size;
  final String name;
  final String ty;
  final bool isHeap;
  final bool isFreed;

  const MemoryRegion({
    required this.addr,
    required this.size,
    required this.name,
    required this.ty,
    required this.isHeap,
    required this.isFreed,
  });

  @override
  int get hashCode =>
      addr.hashCode ^
      size.hashCode ^
      name.hashCode ^
      ty.hashCode ^
      isHeap.hashCode ^
      isFreed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryRegion &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          size == other.size &&
          name == other.name &&
          ty == other.ty &&
          isHeap == other.isHeap &&
          isFreed == other.isFreed;
}

class RunResult {
  final bool success;
  final String output;
  final bool waitingInput;
  final String? error;

  const RunResult({
    required this.success,
    required this.output,
    required this.waitingInput,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      output.hashCode ^
      waitingInput.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          output == other.output &&
          waitingInput == other.waitingInput &&
          error == other.error;
}

class StepResult {
  final StepStatus status;
  final int currentLine;
  final String output;
  final bool waitingInput;

  const StepResult({
    required this.status,
    required this.currentLine,
    required this.output,
    required this.waitingInput,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      currentLine.hashCode ^
      output.hashCode ^
      waitingInput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          currentLine == other.currentLine &&
          output == other.output &&
          waitingInput == other.waitingInput;
}

enum StepStatus { paused, waitingInput, finished, trap }

class TraceEntry {
  final int line;
  final String operation;

  const TraceEntry({required this.line, required this.operation});

  @override
  int get hashCode => line.hashCode ^ operation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraceEntry &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          operation == other.operation;
}

class VisEvent {
  final int ty;
  final int line;
  final int extra0;
  final int extra1;
  final int extra2;
  final String context;

  const VisEvent({
    required this.ty,
    required this.line,
    required this.extra0,
    required this.extra1,
    required this.extra2,
    required this.context,
  });

  @override
  int get hashCode =>
      ty.hashCode ^
      line.hashCode ^
      extra0.hashCode ^
      extra1.hashCode ^
      extra2.hashCode ^
      context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisEvent &&
          runtimeType == other.runtimeType &&
          ty == other.ty &&
          line == other.line &&
          extra0 == other.extra0 &&
          extra1 == other.extra1 &&
          extra2 == other.extra2 &&
          context == other.context;
}
