#!/usr/bin/env python3
"""预编译 runtime_libc 为嵌入产物。

开发流程：
1. 修改 native/runtime_libc/src/*.c
2. 运行 python scripts/precompile_bytecode_libc.py
3. git add native/src/vm/bytecode_libc_data.json native/src/vm/bytecode_libc_index.rs
4. git commit

CI 检查：
    python scripts/precompile_bytecode_libc.py --check
"""

import argparse
import json
import math
import os
import subprocess
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NATIVE_DIR = os.path.join(PROJECT_ROOT, "native")
RUNTIME_LIBC_SRC_DIRS = [
    os.path.join(NATIVE_DIR, "runtime_libc", "src"),
    os.path.join(NATIVE_DIR, "runtime_libc", "cide"),
]
VM_DIR = os.path.join(NATIVE_DIR, "src", "vm")
OUTPUT_JSON = os.path.join(VM_DIR, "bytecode_libc_data.json")
OUTPUT_RS = os.path.join(VM_DIR, "bytecode_libc_index.rs")


def find_cide_cli() -> str:
    """查找 cide_cli 可执行文件路径。"""
    candidates = [
        os.path.join(NATIVE_DIR, "target", "release", "cide_cli.exe"),
        os.path.join(NATIVE_DIR, "target", "release", "cide_cli"),
        os.path.join(NATIVE_DIR, "target", "debug", "cide_cli.exe"),
        os.path.join(NATIVE_DIR, "target", "debug", "cide_cli"),
    ]
    for c in candidates:
        if os.path.exists(c):
            return c
    return ""


def build_cide_cli() -> str:
    """构建 cide_cli，返回可执行文件路径。"""
    print("Building cide_cli...")
    subprocess.run(
        ["cargo", "build", "--release", "--bin", "cide_cli"],
        cwd=NATIVE_DIR,
        check=True,
    )
    exe = find_cide_cli()
    if not exe:
        raise RuntimeError("cide_cli build succeeded but executable not found")
    print(f"  -> {exe}")
    return exe


def precompile(exe: str) -> dict:
    """调用 cide_cli export 预编译 runtime_libc。"""
    sources = []
    for src_dir in RUNTIME_LIBC_SRC_DIRS:
        if os.path.isdir(src_dir):
            sources.extend(
                os.path.join(src_dir, f)
                for f in os.listdir(src_dir)
                if f.endswith(".c") or f.endswith(".cpp")
            )
    sources = sorted(sources)
    # Short-term: .cpp files contain declarations only (no implementations),
    # so we only pass .c files to the bytecode exporter.
    source_paths = [p for p in sources if p.endswith(".c")]

    print(f"Precompiling {len(source_paths)} files:")
    for p in source_paths:
        print(f"  - {os.path.basename(p)}")

    cmd = [exe, "export"] + source_paths + ["-o", OUTPUT_JSON]
    subprocess.run(cmd, check=True)

    with open(OUTPUT_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"  code_len: {data['code_len']}")
    print(f"  func_count: {len(data['func_index'])}")
    print(f"  globals_size: {data['globals_size']}")
    return data


def generate_index_rs(data: dict) -> str:
    """生成 bytecode_libc_index.rs。"""
    raw_func_index = data["func_index"]
    base_index = 1000
    globals_reserved = max(1024, math.ceil(data["globals_size"] / 1024) * 1024)
    code_len = data["code_len"]

    # 将原始索引重新映射为固定索引（从 BASE_INDEX 开始）
    # 原始索引通常是 1..N，我们需要映射为 1000..1000+N-1
    sorted_raw = sorted(raw_func_index.items(), key=lambda x: x[1])
    func_index = {}
    for i, (name, _) in enumerate(sorted_raw):
        func_index[name] = base_index + i

    # 按固定索引排序
    sorted_funcs = sorted(func_index.items(), key=lambda x: x[1])

    lines = [
        "// AUTO-GENERATED by scripts/precompile_bytecode_libc.py",
        "// DO NOT EDIT MANUALLY",
        "//",
        "// To regenerate:",
        "//   python scripts/precompile_bytecode_libc.py",
        "",
        f"pub const BYTECODE_LIBC_CODE_LEN: usize = {code_len};",
        f"pub const BYTECODE_LIBC_BASE_INDEX: i32 = {base_index};",
        f"pub const BYTECODE_LIBC_GLOBALS_RESERVED: u32 = {globals_reserved};",
        f"pub const BYTECODE_LIBC_FUNC_COUNT: usize = {len(func_index)};",
        "",
        "/// Bytecode Libc 中所有可用的函数名（供索引查询使用）。",
        "/// 注意：并非所有函数都默认走 Bytecode 路径，",
        "/// 实际路径由 `host_func_id::BYTECODE_LIBC_PURE_FUNCS` 控制。",
        "pub const BYTECODE_LIBC_ALL_FUNCS: &[&str] = &[",
    ]
    for name, _ in sorted_funcs:
        lines.append(f'    "{name}",')
    lines.append("];")
    lines.append("")
    lines.append("/// 将函数名解析为 Bytecode Libc 固定索引。")
    lines.append("pub fn bytecode_libc_index(name: &str) -> Option<i32> {")
    lines.append("    match name {")
    for name, idx in sorted_funcs:
        lines.append(f'        "{name}" => Some({idx}),')
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("/// 判断函数是否在 Bytecode Libc 预编译产物中存在。")
    lines.append("pub fn is_bytecode_libc(name: &str) -> bool {")
    lines.append("    bytecode_libc_index(name).is_some()")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def write_outputs(data: dict) -> None:
    """写入 JSON 和 Rust 常量文件。"""
    rs_content = generate_index_rs(data)
    with open(OUTPUT_RS, "w", encoding="utf-8") as f:
        f.write(rs_content)
    print(f"Written: {OUTPUT_RS}")


def check_up_to_date() -> bool:
    """检查预编译产物是否与 C 源码同步。"""
    if not os.path.exists(OUTPUT_JSON) or not os.path.exists(OUTPUT_RS):
        return False

    json_mtime = os.path.getmtime(OUTPUT_JSON)
    src_dir = os.path.join(NATIVE_DIR, "runtime_libc", "src")
    for fname in os.listdir(src_dir):
        if fname.endswith(".c") or fname.endswith(".h"):
            fpath = os.path.join(src_dir, fname)
            if os.path.getmtime(fpath) > json_mtime:
                return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Precompile runtime_libc Bytecode")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if precompiled artifacts are up-to-date (CI mode)",
    )
    args = parser.parse_args()

    if args.check:
        if check_up_to_date():
            print("Precompiled artifacts are up-to-date.")
            return 0
        else:
            print(
                "ERROR: Precompiled artifacts are out-of-date. "
                "Run: python scripts/precompile_bytecode_libc.py",
                file=sys.stderr,
            )
            return 1

    exe = find_cide_cli()
    if not exe:
        exe = build_cide_cli()

    data = precompile(exe)
    write_outputs(data)
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
