// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An activated concept with its 1-hop neighbors.
class ActivatedConcept {
  final ConceptNode node;
  final String activatedBy;
  final List<NeighborConcept> neighbors;

  const ActivatedConcept({
    required this.node,
    required this.activatedBy,
    required this.neighbors,
  });

  @override
  int get hashCode => node.hashCode ^ activatedBy.hashCode ^ neighbors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivatedConcept &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          activatedBy == other.activatedBy &&
          neighbors == other.neighbors;
}

/// A directed edge between two concepts.
class ConceptEdge {
  final String from;
  final String to;
  final String relation;
  final double strength;

  const ConceptEdge({
    required this.from,
    required this.to,
    required this.relation,
    required this.strength,
  });

  @override
  int get hashCode =>
      from.hashCode ^ to.hashCode ^ relation.hashCode ^ strength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConceptEdge &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          relation == other.relation &&
          strength == other.strength;
}

/// A concept node in the knowledge graph.
class ConceptNode {
  final String id;
  final String domain;
  final String title;
  final String description;
  final int difficulty;
  final List<String> relatedCardIds;

  const ConceptNode({
    required this.id,
    required this.domain,
    required this.title,
    required this.description,
    required this.difficulty,
    required this.relatedCardIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      domain.hashCode ^
      title.hashCode ^
      description.hashCode ^
      difficulty.hashCode ^
      relatedCardIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConceptNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          domain == other.domain &&
          title == other.title &&
          description == other.description &&
          difficulty == other.difficulty &&
          relatedCardIds == other.relatedCardIds;
}

/// A neighboring concept in the activated sub-graph.
class NeighborConcept {
  final ConceptNode node;
  final String relation;
  final double strength;
  final bool isPrerequisite;

  const NeighborConcept({
    required this.node,
    required this.relation,
    required this.strength,
    required this.isPrerequisite,
  });

  @override
  int get hashCode =>
      node.hashCode ^
      relation.hashCode ^
      strength.hashCode ^
      isPrerequisite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeighborConcept &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          relation == other.relation &&
          strength == other.strength &&
          isPrerequisite == other.isPrerequisite;
}
