// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A complete learning path for a single misconception.
class LearningPath {
  final String targetMisconceptionId;
  final String targetMisconceptionName;

  /// Estimated time to complete, in minutes.
  final int estimatedTimeMinutes;
  final List<PathStep> steps;

  const LearningPath({
    required this.targetMisconceptionId,
    required this.targetMisconceptionName,
    required this.estimatedTimeMinutes,
    required this.steps,
  });

  @override
  int get hashCode =>
      targetMisconceptionId.hashCode ^
      targetMisconceptionName.hashCode ^
      estimatedTimeMinutes.hashCode ^
      steps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LearningPath &&
          runtimeType == other.runtimeType &&
          targetMisconceptionId == other.targetMisconceptionId &&
          targetMisconceptionName == other.targetMisconceptionName &&
          estimatedTimeMinutes == other.estimatedTimeMinutes &&
          steps == other.steps;
}

/// A single step in a recommended learning path.
class PathStep {
  /// Step type identifier: "ReadKnowledgeCard" | "StudyTemplate" | "CompleteExercise" | "ReviewOwnCode"
  final String stepType;

  /// Human-readable title shown in the UI.
  final String title;

  /// Detailed description of what the student should do.
  final String detail;

  /// Target ID (card_id / template_id / exercise_id).
  final String targetId;

  /// Lines to highlight when studying a template (1-based).
  final Int32List highlightLines;

  const PathStep({
    required this.stepType,
    required this.title,
    required this.detail,
    required this.targetId,
    required this.highlightLines,
  });

  @override
  int get hashCode =>
      stepType.hashCode ^
      title.hashCode ^
      detail.hashCode ^
      targetId.hashCode ^
      highlightLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathStep &&
          runtimeType == other.runtimeType &&
          stepType == other.stepType &&
          title == other.title &&
          detail == other.detail &&
          targetId == other.targetId &&
          highlightLines == other.highlightLines;
}
