// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A single compile/run record from the student’s history.
class CompileRecord {
  /// Unix timestamp in milliseconds.
  final PlatformInt64 timestampMs;

  /// Whether compilation succeeded.
  final bool success;

  /// Error / warning / hint codes produced in this compile.
  final Int32List errorCodes;

  /// Runtime trap message, if any.
  final String? trapMessage;

  const CompileRecord({
    required this.timestampMs,
    required this.success,
    required this.errorCodes,
    this.trapMessage,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      success.hashCode ^
      errorCodes.hashCode ^
      trapMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompileRecord &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          success == other.success &&
          errorCodes == other.errorCodes &&
          trapMessage == other.trapMessage;
}

/// A detected misconception with confidence score.
class DetectedMisconception {
  final String patternId;
  final String patternName;
  final String description;

  /// How many records in the window matched.
  final int occurrenceCount;

  /// 0.0 ~ 1.0  (occurrences / min(window, min_occurrences) 的变体).
  final double confidence;

  const DetectedMisconception({
    required this.patternId,
    required this.patternName,
    required this.description,
    required this.occurrenceCount,
    required this.confidence,
  });

  @override
  int get hashCode =>
      patternId.hashCode ^
      patternName.hashCode ^
      description.hashCode ^
      occurrenceCount.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetectedMisconception &&
          runtimeType == other.runtimeType &&
          patternId == other.patternId &&
          patternName == other.patternName &&
          description == other.description &&
          occurrenceCount == other.occurrenceCount &&
          confidence == other.confidence;
}
