// AUTO-GENERATED by scripts/precompile_bytecode_libc.py
// DO NOT EDIT MANUALLY
//
// To regenerate:
//   python scripts/precompile_bytecode_libc.py

pub const BYTECODE_LIBC_CODE_LEN: usize = 790;
pub const BYTECODE_LIBC_BASE_INDEX: i32 = 1000;
pub const BYTECODE_LIBC_GLOBALS_RESERVED: u32 = 1024;
pub const BYTECODE_LIBC_FUNC_COUNT: usize = 22;

/// Bytecode Libc 中所有可用的函数名（供索引查询使用）。
/// 注意：并非所有函数都默认走 Bytecode 路径，
/// 实际路径由 `host_func_id::BYTECODE_LIBC_PURE_FUNCS` 控制。
pub const BYTECODE_LIBC_ALL_FUNCS: &[&str] = &[
    "isdigit",
    "isalpha",
    "islower",
    "isupper",
    "tolower",
    "toupper",
    "isspace",
    "isalnum",
    "isprint",
    "iscntrl",
    "isxdigit",
    "abs",
    "atoi",
    "srand",
    "rand",
    "strlen",
    "strcmp",
    "strcpy",
    "strcat",
    "strncpy",
    "memcpy",
    "memmove",
];

/// 将函数名解析为 Bytecode Libc 固定索引。
pub fn bytecode_libc_index(name: &str) -> Option<i32> {
    match name {
        "isdigit" => Some(1000),
        "isalpha" => Some(1001),
        "islower" => Some(1002),
        "isupper" => Some(1003),
        "tolower" => Some(1004),
        "toupper" => Some(1005),
        "isspace" => Some(1006),
        "isalnum" => Some(1007),
        "isprint" => Some(1008),
        "iscntrl" => Some(1009),
        "isxdigit" => Some(1010),
        "abs" => Some(1011),
        "atoi" => Some(1012),
        "srand" => Some(1013),
        "rand" => Some(1014),
        "strlen" => Some(1015),
        "strcmp" => Some(1016),
        "strcpy" => Some(1017),
        "strcat" => Some(1018),
        "strncpy" => Some(1019),
        "memcpy" => Some(1020),
        "memmove" => Some(1021),
        _ => None,
    }
}

/// 判断函数是否在 Bytecode Libc 预编译产物中存在。
pub fn is_bytecode_libc(name: &str) -> bool {
    bytecode_libc_index(name).is_some()
}

