#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCode {
    Nop = 0,
    PushConst = 1,
    LoadLocal = 2,
    StoreLocal = 3,
    LoadGlobal = 4,
    StoreGlobal = 5,
    GetFrameBase = 6,
    Pop = 7,
    Dup = 8,
    Swap = 9,
    LoadMem = 10,
    StoreMem = 11,
    LoadMemByte = 12,
    StoreMemByte = 13,
    Add = 14,
    Sub = 15,
    Mul = 16,
    Div = 17,
    Mod = 18,
    Neg = 19,
    Eq = 20,
    Ne = 21,
    Lt = 22,
    Le = 23,
    Gt = 24,
    Ge = 25,
    And = 26,
    Or = 27,
    Not = 28,
    Jump = 29,
    JumpIfZero = 30,
    JumpIfNotZero = 31,
    Call = 32,
    CallHost = 33,
    Ret = 34,
    RetVoid = 35,
    StepEvent = 36,
    TrapBounds = 37,
}

impl OpCode {
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(OpCode::Nop),
            1 => Some(OpCode::PushConst),
            2 => Some(OpCode::LoadLocal),
            3 => Some(OpCode::StoreLocal),
            4 => Some(OpCode::LoadGlobal),
            5 => Some(OpCode::StoreGlobal),
            6 => Some(OpCode::GetFrameBase),
            7 => Some(OpCode::Pop),
            8 => Some(OpCode::Dup),
            9 => Some(OpCode::Swap),
            10 => Some(OpCode::LoadMem),
            11 => Some(OpCode::StoreMem),
            12 => Some(OpCode::LoadMemByte),
            13 => Some(OpCode::StoreMemByte),
            14 => Some(OpCode::Add),
            15 => Some(OpCode::Sub),
            16 => Some(OpCode::Mul),
            17 => Some(OpCode::Div),
            18 => Some(OpCode::Mod),
            19 => Some(OpCode::Neg),
            20 => Some(OpCode::Eq),
            21 => Some(OpCode::Ne),
            22 => Some(OpCode::Lt),
            23 => Some(OpCode::Le),
            24 => Some(OpCode::Gt),
            25 => Some(OpCode::Ge),
            26 => Some(OpCode::And),
            27 => Some(OpCode::Or),
            28 => Some(OpCode::Not),
            29 => Some(OpCode::Jump),
            30 => Some(OpCode::JumpIfZero),
            31 => Some(OpCode::JumpIfNotZero),
            32 => Some(OpCode::Call),
            33 => Some(OpCode::CallHost),
            34 => Some(OpCode::Ret),
            35 => Some(OpCode::RetVoid),
            36 => Some(OpCode::StepEvent),
            37 => Some(OpCode::TrapBounds),
            _ => None,
        }
    }
}
