// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// High-level code intent categories.
enum CodeIntent { sort, search, traverse, compute, transform, unknown }

/// A scored intent guess.
class IntentScore {
  final CodeIntent intent;
  final int score;
  final List<String> reasons;

  const IntentScore({
    required this.intent,
    required this.score,
    required this.reasons,
  });

  @override
  int get hashCode => intent.hashCode ^ score.hashCode ^ reasons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntentScore &&
          runtimeType == other.runtimeType &&
          intent == other.intent &&
          score == other.score &&
          reasons == other.reasons;
}
